name: "Jeedom"
description: "Jeedom Home Automation Platform"
version: "4.4"
slug: "jeedom_ha"
init: false
arch:
  - amd64
  - aarch64
startup: "services"
boot: "auto"
image: "jeedom/jeedom"
ports:
  80/tcp: 40080
  443/tcp: 40443
ingress: true
ingress_port: 80
watchdog: "http://[HOST]:[PORT:80]"
map:
  - addon_config:/data                 # configurazioni addon generali
  - addon_config/html:/var/www/html    # HTML di Jeedom
  - addon_config/db:/var/lib/mysql     # database di Jeedom
