name: Sync Jeedom Docker Version

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  sync-jeedom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest Jeedom Docker tag
        id: docker
        run: |
          TAG=$(curl -s https://registry.hub.docker.com/v2/repositories/jeedom/jeedom/tags \
            | jq -r '.results[].name' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V \
            | tail -n 1)
          echo "version=$TAG" >> $GITHUB_OUTPUT

      - name: Update Jeedom-HA addon version
        run: |
          FILE="Jeedom-HA/config.json"
          CURRENT=$(jq -r '.version' "$FILE")
          LATEST=${{ steps.docker.outputs.version }}

          if [ "$CURRENT" != "$LATEST" ]; then
            jq ".version = \"$LATEST\"" "$FILE" > tmp.json
            mv tmp.json "$FILE"
          else
            echo "Jeedom addon already up to date"
            exit 0
          fi

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Jeedom-HA/config.json
          git commit -m "chore(jeedom): bump to ${{ steps.docker.outputs.version }}"
          git push
